### ISSUE TITLE
'AnsibleModule' object has not attribute 'constants" ... blockinfile.py

### ISSUE THREAD

**Issue by worsco** [ansible/ansible-modules-extras#2348]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

blockinfile
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

rpm -qa | grep ^ansible
ansible-2.1.0.0-0.git201605271344.2452bd2.stable21.el7.centos.noarch

```
##### CONFIGURATION

No changes
##### OS / ENVIRONMENT

CentOS Linux release 7.2.1511 (Core)
##### SUMMARY

The module, blockinfile, appears to no longer work in 2.1.0.
##### STEPS TO REPRODUCE

Execute the following:

ansible-playbook -vvv test-blockinfile.yml

test-blockinfile.yml contains:

```

---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:

  - name: A very simple blockinfile test
    blockinfile:
      dest: ~/testfile
      insertbefore: BOF
      block: |
        This is my block
        This should work
        It is very basic test
      create: yes

```

##### EXPECTED RESULTS

No errors.
##### ACTUAL RESULTS

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_lq3WNb/ansible_module_blockinfile.py", line 311, in <module>
    main()
  File "/tmp/ansible_lq3WNb/ansible_module_blockinfile.py", line 247, in main
    if module.constants['ANSIBLE_VERSION'].startswith('1.'):
AttributeError: 'AnsibleModule' object has no attribute 'constants'

```

**Comment by worsco** [comment]
ISSUE SOLVED

I pulled down ansible via git repository to create an RPM via:

$ git clone git://github.com/ansible/ansible.git --recursive
$ cd ./ansible
$ git pull --rebase

However, I did not do the following:

$ git submodule update --init --recursive

From the section http://docs.ansible.com/ansible/intro_installation.html#running-from-source:
"Note when updating ansible, be sure to not only update the source tree,
but also the “submodules” in git which point at Ansible’s own modules
(not the same kind of modules, alas)."

After performing the above, then building and installing the RPM, the blockinfile module works.

$ make rpm
$ sudo rpm -Uvh ./rpm-build/ansible-*.noarch.rpm

Hopefully this helps someone else, too.
