### ISSUE TITLE
Consul module for 2.1 fails with wrong parameter name for python-consul constructor (

### ISSUE THREAD

**Issue by wouterla** [ansible/ansible-modules-extras#2114]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

clustering/consul.py
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /Users/wouter/data/src/..../ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
gathering = smart
fact_caching = jsonfile
fact_caching_connection = plays/cache
fact_caching_timeout = 86400
nocows = 1

[ssh_connection]
ssh_args = -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
```
##### SUMMARY

Consul tasks fail with a message `__init__() got an unexpected keyword argument 'validate_certs`
This is because the boolean value has a different name ('verify') in the constructor for the Consul class. 

The code involved looks like this (in `clustering/consul.py`):

```
def get_consul_api(module, token=None):
    return consul.Consul(host=module.params.get('host'),
                         port=module.params.get('port'),
                         scheme=module.params.get('scheme'),
                         validate_certs=module.params.get('validate_certs'),
                         token=module.params.get('token'))
```

Simply changing the call to use:

```
                         verify=module.params.get('validate_certs'),
```

Seems to work to fix this. I'm not making a pull request, as I have no idea of any broader impact/versioning/etc.
##### STEPS TO REPRODUCE

Any simple playbook for consul should have this issue.

```
- hosts: localhost
  become: no
  tasks:
    - name: Register {service} with consul.
      consul:
        host: 192.168.56.11
        service_name: "test"
        service_address: "192.168.56.51"
        service_port: 9090
        interval: 60s
        http: /
```
##### EXPECTED RESULTS

It to try and contact a consul host.
##### ACTUAL RESULTS

The full error message:

```
fatal: [dev-swarm-manager]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"check_host": null, "check_id": null, "check_name": null, "check_node": null, "host": "localhost", "http": "/", "interval": "60s", "notes": null, "port": 8500, "scheme": "http", "script": null, "service_address": "192.168.56.101", "service_id": null, "service_name": "identity", "service_port": 9090, "state": "present", "tags": ["latest"], "timeout": null, "token": null, "ttl": null, "validate_certs": true}, "module_name": "consul"}, "msg": "__init__() got an unexpected keyword argument 'validate_certs'"}
```

**Comment by chouseknecht** [comment]
@sgargan do you have time to take a look at this?

**Comment by JakeWorrell** [comment]
Hi, I'm experiencing this issue at the moment. What can I do to work around it? Is there any way I can install Ansible and/or extras from the development branch?

**Comment by jamesmaidment** [comment]
@JakeWorrell try downgrading to Ansible [2.0.2.0](https://github.com/ansible/ansible/releases/tag/v2.0.2.0-1) until the fix is released.

**Comment by cwarner-mdsol** [comment]
Serenity now.

**Comment by boonen** [comment]
This used to work with the stable-2.1 branch, but a few days ago it stopped working. Is the solution broken by another commit?

**Comment by resmo** [comment]
@boonen could you open an issue with some more information, traceback and exact version you use?

**Comment by conatus** [comment]
Is there any fix for this or workaround?

**Comment by dustinalan** [comment]
bump, any updates? This module is currently affecting our PR's

**Comment by resmo** [comment]
this fix is included in v2.1.1.

If you see issues, please open a new ticket with all the infos.

**Comment by ghost** [comment]
@resmo looks like I'm still getting this error in travis. Am I missing something? Should I debug the code further you think and open a new ticket?

```
$ ansible --version
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```

.....

```
- hosts: builder
  tasks:
  - name: Check for an existing Instance
    ec2_remote_facts:
      region: "us-east-1"
      filters:
        "tag:Name": "name-of-our-tag"
```

.....

`TASK [Check for an existing Instance] ******************************************`

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: __init__() got an unexpected keyword argument 'validate_certs'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_mizHx5/ansible_module_ec2_remote_facts.py\", line 169, in <module>\n    main()\n  File \"/tmp/ansible_mizHx5/ansible_module_ec2_remote_facts.py\", line 156, in main\n    connection = connect_to_aws(boto.ec2, region, **aws_connect_params)\n  File \"/tmp/ansible_mizHx5/ansible_modlib.zip/ansible/module_utils/ec2.py\", line 208, in connect_to_aws\n  File \"/usr/lib/python2.7/dist-packages/boto/ec2/__init__.py\", line 55, in connect_to_region\n    for region in regions(**kw_params):\n  File \"/usr/lib/python2.7/dist-packages/boto/ec2/__init__.py\", line 38, in regions\n    c = EC2Connection(**kw_params)\nTypeError: __init__() got an unexpected keyword argument 'validate_certs'\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}`
