### PR TITLE
Update xenserver_facts module to work with xenserver 6.5

### PR DESCRIPTION
**Pull request by jrandall**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME
- xenserver_facts
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

xenserver_facts did not work with XenServer 6.5 because it appears than XenAPI have changed 
some data structures. This update makes changes that make it work with 6.5. I am not certain whether it still works with XenServer < 6.5 as I have no such servers to test with, so it would be great if someone can test that. 

Before this change, running against XenServer 6.5 yields the following error:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'list' object has no attribute 'iteritems'
dc4virt2 | FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_GYY4_W/ansible_module_xenserver_facts.py\", line 195, in ?\n    main()\n  File \"/tmp/ansible_GYY4_W/ansible_module_xenserver_facts.py\", line 175, in main\n    xs_vms = get_vms(session)\n  File \"/tmp/ansible_GYY4_W/ansible_module_xenserver_facts.py\", line 142, in get_vms\n    vms = change_keys(recs, key='uuid')\n  File \"/tmp/ansible_GYY4_W/ansible_module_xenserver_facts.py\", line 121, in change_keys\n    for ref, rec in recs.iteritems():\nAttributeError: 'list' object has no attribute 'iteritems'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "parsed": false
}
```

After this change, running against XenServer 6.5 yields a full set of gathered facts for XenServer VMs.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @jrandall. To the current maintainers, @andyhky please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]
