### ISSUE TITLE
os_project requires python-shade 1.8.1 or higher

### ISSUE THREAD

**Issue by fitschn** [ansible/ansible-modules-extras#2805]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

os_project
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### OS / ENVIRONMENT

Ubuntu 16.04
##### SUMMARY

With ansible 2.1.1.0 the os_project module requires python-shade 1.8 or higher. But ubuntu ships python-shade 1.5, so this module does not work anymore. The os_project module is working correctly with ansible 2.1.0.0
##### STEPS TO REPRODUCE

```
- name: Create OpenStack project
  os_project:
    cloud: my_cloud
    name: projectname
    description: Test Project
    domain_id: default
    endpoint_type: internal
```

##### EXPECTED RESULTS

A new project in OpenStack
##### ACTUAL RESULTS

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_g7eGSB/ansible_module_os_project.py", line 222, in <module>
    main()
  File "/tmp/ansible_g7eGSB/ansible_module_os_project.py", line 183, in main
    project = cloud.get_project(name, domain_id=domain)
TypeError: get_project() got an unexpected keyword argument 'domain_id'
```

**Comment by ansibot** [comment]
@emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)
